"""add description to products

Revision ID: ec8acd45acb7
Revises: 80b672298fbf
Create Date: 2026-05-29 13:36:23.199061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec8acd45acb7'
down_revision: Union[str, Sequence[str], None] = '80b672298fbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Колонка NOT NULL: на первом шаге задаём server_default, чтобы уже
    # существующие строки получили валидное значение и не нарушали ограничение.
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'description',
                sa.String(length=1000),
                nullable=False,
                server_default='',
            )
        )

    # На втором шаге убираем серверный default — теперь все строки уже
    # содержат значения, и итоговая схема совпадает с моделью (NOT NULL без default).
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('description', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
